num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

print("\nAddition: ", num1 + num2)
print("Subtraction: ", num1 - num2)
print("Multiplication: ", num1 * num2)
print("Division: ", num1 / num2)
print("Floor-division: ", num1 // num2)
print("Exponent: ", num1 ** num2)
print("Modulous: ", num1 % num2)